trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: true

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(solution)'
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- script: echo "Variable name before publish:$(Build.ArtifactStagingDirectory)"
- task: DotNetCoreCLI@2
  inputs:
    projects: '$(solution)'
    command: 'publish'
    configuration: '--c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- script: echo "Variable name after publish:$(Build.ArtifactStagingDirectory)"

- script: echo "Variable name after publish BinariesDirectory:$(Build.BinariesDirectory)"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: echo "Variable name after publish build artifact:$(Build.ArtifactStagingDirectory)"