trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: BuildStage
    displayName: 'Build'
    jobs:
      - job: Buildjob
        steps:
        
        - task: DotNetCoreCLI@2
          displayName: 'Restore Nuget' 
          inputs:
            command: 'restore'
            projects: '$(solution)'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: 'Build solution' 
          inputs:
            projects: '$(solution)'
            command: 'build'
            arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

        - task: DotNetCoreCLI@2
          displayName: 'Run tests'
          inputs:
            command: 'test'
            projects: 'TestProject\TestProject.csproj'
            arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage"'      
        - task: PublishCodeCoverageResults@2
          displayName: 'Publish code coverage' 
          inputs:
            failIfCoverageEmpty: true
            summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

        - task: DotNetCoreCLI@2
          displayName: 'Publish solution' 
          inputs:
            projects: '$(solution)'
            command: 'publish'
            configuration: '--c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: 'drop'
            publishLocation: 'pipeline'

  - stage: DeployStage
    displayName: 'Deploy'
    jobs:
      - job:
        steps:
        

        # - task: DownloadBuildArtifacts@1
        #   inputs:
        #     buildType: 'specific'
        #     project: '067649f8-74f8-4f10-a456-d4201528fd64'
        #     pipeline: '2'
        #     buildVersionToDownload: 'latest'
        #     downloadType: 'specific'
        #     downloadPath: '$(System.ArtifactsDirectory)'
        # - script: |
        #     echo "Structure of work folder of this pipeline:"
        #     tree $(System.ArtifactsDirectory) /f
        #     echo "Build.ArtifactsDirectory:" 
        #     echo "$(Build.ArtifactsDirectory)"
          

        # - task: DownloadBuildArtifacts@1
        #   inputs:
        #     buildType: 'current'
        #     downloadType: 'single'
        #     artifactName: 'drop'
        #     downloadPath: '$(System.ArtifactsDirectory)'
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Pipeline.Workspace)'
        - powershell: |
            Compress-Archive -Path "$(Pipeline.Workspace)/drop/*" -DestinationPath "$(Pipeline.Workspace)/drop.zip" -Force

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'DevopsLearnAppService'
            appType: 'webApp'
            WebAppName: 'Dev-DevOpsLearn'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
        

          
        

