stages:
  - stage: DeployStage$[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['env']]
    displayName: "Deployed to $[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['env']]"
    dependsOn: ChooseEnvStage
    jobs:
      - deployment: $[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['env']]
        displayName: $[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['env']]
        environment: $[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['env']]
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'
            
                - powershell: |
                    Compress-Archive -Path "$(Pipeline.Workspace)/drop/*" -DestinationPath "$(Pipeline.Workspace)/drop.zip" -Force

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'DevopsLearnAppService'
                    appType: 'webApp'
                    WebAppName: $[dependencies.ChooseEnvStage.ChooseEnvJob.outputs['appservice']]
                    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'