
stages:
  - stage: DeployStage
    dependsOn: ChooseEnvStage
    variables: 
        environmentname:  $[ stageDependencies.ChooseEnvStage.ChooseEnvJob.outputs['storeenvvalue.env'] ]
        appServicename: $[ stageDependencies.ChooseEnvStage.ChooseEnvJob.outputs['storeappservicevalue.appservice'] ]
    displayName: 'Deploy'
    jobs:
      - job: tempjob
        steps:
        - task: Bash@3
          name: storeappservicevalue
          inputs:
                  targetType: 'inline'
                  script: |
                    echo $(environmentname)

      - deployment:  Deploy
        displayName: 'Deploy stage' 
        dependsOn: tempjob
        ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
           environment: 'Production'
        ${{ if eq(variables['Build.SourceBranchName'], 'QA') }}:
            environment: 'QA'

        ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
            environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                        buildType: 'current'
                        artifactName: 'drop'
                        targetPath: '$(Pipeline.Workspace)/drop'
              - task: Bash@3
                inputs:
                    targetType: 'inline'
                    script: |
                      echo 'environment name:' $(environmentname)                   
                      echo 'app service name:' $(appServicename)
              - task: AzureRmWebAppDeployment@4
                inputs:
                        ConnectionType: 'AzureRM'
                        azureSubscription: 'DevopsLearnAppService'
                        appType: 'webApp'
                        WebAppName: $(appServicename)
                        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'