parameters:
- name: environment
  type: string
  default: 'dev'
- name: appservice
  type: string
  default: 'Dev-DevOpsLearn'


jobs:
  - deployment:  Deploy
    displayName: 'Deploy stage' 
    environment: ${{parameters.environment}} 
    strategy:
       runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
                    buildType: 'current'
                    artifactName: 'drop'
                    targetPath: '$(Pipeline.Workspace)/drop'

          - task: AzureRmWebAppDeployment@4
            inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'DevopsLearnAppService'
                    appType: 'webApp'
                    WebAppName: ${{parameters.environment}} 
                    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'