trigger:
- main
- dev
- QA

pool:
  vmImage: 'windows-latest'

stages:
    - stage: firststage
      jobs: 
        - job: firstjob
          steps:
            - task: Bash@3
              name: storevalue
              inputs:
                targetType: 'inline'
                script: |
                  $env="Hello"
                  echo "##vso[task.setvariable variable=env;isOutput=true]$env"      
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  echo '$(storevalue.env)'
    - stage: SecondStage
      jobs: 
        - job: secondjob
          steps: 
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo $[ stageDependencies.firststage.firstjob.outputs["storevalue.env"] ]



