trigger:
- main
- dev
- QA

pool:
  vmImage: 'windows-latest'

stages:
    - stage: firststage
      jobs: 
        - job: firstjob
          steps:
            - task: Bash@3
              name: storevalue
              inputs:
                targetType: 'inline'
                script: |
                  $env: "$(./1.sh env master)"
                  echo "##vso[task.setvariable variable=env]$env"      
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  
                  echo 'Hello world ' $(env);
    - stage: SecondStage
      jobs: 
        - job: secondjob
          steps: 
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo $[ dependencies.firststage.firstjob.outputs["storevalue.env"] ]'


