trigger:
- main
- dev
- QA

pool:
  vmImage: 'windows-latest'

stages:
    - stage: firststage
      jobs: 
        - job: firstjob
          steps:
          
            - task: Bash@3
              name: storevalue
              inputs:
                targetType: 'inline'
                script: |
                  env="$(./1.sh env $(Build.SourceBranchName))"
                  echo "##vso[task.setvariable variable=env;isOutput=true]$env"       
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  echo '$(storevalue.env)'
    - stage: SecondStage
      jobs: 
        - job: secondjob
          variables:
            out : $[ stageDependencies.firststage.firstjob.outputs['storevalue.env'] ] 
          steps: 
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo $(out)



